# Generated by Django 5.2.4 on 2026-05-30 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('active', models.BooleanField(default=True)),
                ('schedule', models.PositiveSmallIntegerField(choices=[(1, 'каждую минуту'), (5, 'каждые 5 минут'), (10, 'каждые 10 минут'), (15, 'каждые 15 минут'), (30, 'каждые 30 минут'), (60, 'каждый час')], default=5)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CameraAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['camera'],
            },
        ),
        migrations.CreateModel(
            name='ZoneStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='YouTubeVideo',
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['active'], name='backend_api_active_070bd5_idx'),
        ),
        migrations.AddField(
            model_name='cameraanalysis',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='backend_api.camera'),
        ),
        migrations.AddField(
            model_name='zone',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='backend_api.camera'),
        ),
        migrations.AddField(
            model_name='zonestatistics',
            name='camera_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_analyses', to='backend_api.cameraanalysis'),
        ),
        migrations.AddField(
            model_name='zonestatistics',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='backend_api.zone'),
        ),
        migrations.AddIndex(
            model_name='cameraanalysis',
            index=models.Index(fields=['camera', '-date'], name='backend_api_camera__2dc8af_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['camera'], name='backend_api_camera__8d610d_idx'),
        ),
    ]
