# Generated by Django 5.2.4 on 2026-05-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_camera_cameraanalysis_zone_zonestatistics_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('camera', 'name'), name='unique_zone_name_per_camera'),
        ),
    ]
