# Generated by Django 5.2.4 on 2026-05-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_zone_unique_zone_name_per_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraanalysis',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='backend_api.camera'),
        ),
        migrations.AlterField(
            model_name='zonestatistics',
            name='camera_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_analysis', to='backend_api.cameraanalysis'),
        ),
    ]
