# Generated by Django 5.2.4 on 2026-05-31 07:27

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_cameraanalysis_camera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='backend_api.camera')),
            ],
        ),
    ]
