# Generated by Django 5.2.4 on 2026-06-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_cameraauth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cameraanalysis',
            name='backend_api_camera__2dc8af_idx',
        ),
        migrations.RemoveIndex(
            model_name='zone',
            name='backend_api_camera__8d610d_idx',
        ),
        migrations.AlterField(
            model_name='camera',
            name='schedule',
            field=models.PositiveSmallIntegerField(choices=[(1, 'каждую минуту'), (5, 'каждые 5 минут'), (10, 'каждые 10 минут'), (15, 'каждые 15 минут'), (30, 'каждые 30 минут'), (60, 'каждый час')], default=1),
        ),
    ]
