# Generated by Django 5.2.4 on 2026-06-07 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('current', 'Текущая посещаемость'), ('histogram', 'Гистограмма')], max_length=32)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cameras', models.ManyToManyField(blank=True, related_name='widgets', to='backend_api.camera')),
                ('zones', models.ManyToManyField(blank=True, related_name='widgets', to='backend_api.zone')),
            ],
        ),
        migrations.CreateModel(
            name='HistogramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(choices=[('6h', '6 часов'), ('1d', '1 день'), ('7d', '7 дней'), ('30d', '30 дней')], default='1d', max_length=8)),
                ('widget', models.OneToOneField(limit_choices_to={'widget_type': 'histogram'}, on_delete=django.db.models.deletion.CASCADE, related_name='histogram_config', to='backend_api.widget')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.camera')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_cameras', to='backend_api.widget')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_zones', to='backend_api.widget')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.zone')),
            ],
        ),
    ]
