# Generated by Django 5.2.4 on 2026-06-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_widget_histogramconfig_widgetcamera_widgetzone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='cameras',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='zones',
        ),
    ]
