# Generated by Django 5.2.4 on 2026-06-08 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_remove_widget_cameras_remove_widget_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetcamera',
            name='capacity',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='widgetzone',
            name='capacity',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
