# Generated by Django 5.2.4 on 2026-06-08 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_alter_widgetcamera_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetcamera',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam', to='backend_api.camera'),
        ),
        migrations.AlterField(
            model_name='widgetzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zon', to='backend_api.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='widgetcamera',
            unique_together={('widget', 'camera')},
        ),
        migrations.AlterUniqueTogether(
            name='widgetzone',
            unique_together={('widget', 'zone')},
        ),
    ]
