# Generated by Django 5.2.4 on 2026-06-08 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_alter_widgetcamera_camera_alter_widgetzone_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetcamera',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_widgets', to='backend_api.camera'),
        ),
        migrations.AlterField(
            model_name='widgetzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_widgets', to='backend_api.zone'),
        ),
    ]
