# Generated by Django 5.2.4 on 2026-06-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_camera_user_alter_widget_widget_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='camera',
            name='backend_api_active_070bd5_idx',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='active',
        ),
    ]
